# Generated by Django 4.1.2 on 2022-12-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
