# Generated by Django 4.1.2 on 2022-12-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='items',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='unique_migration_host_combination'),
        ),
    ]
