# Generated by Django 4.1.2 on 2022-12-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_rename_items_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='project',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
